// <auto-generated />
using AAAATHIDEMO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AAAATHIDEMO.Migrations
{
    [DbContext(typeof(AAAATHIDEMOContext))]
    [Migration("20230802073449_Create_Table_Faculty")]
    partial class Create_Table_Faculty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("AAAATHIDEMO.Models.Dongvat", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChungLoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Dongvat");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Dongvat");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AAAATHIDEMO.Models.Faculty", b =>
                {
                    b.Property<string>("FaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FaID");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("AAAATHIDEMO.Models.Student", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("AAAATHIDEMO.Models.Cat", b =>
                {
                    b.HasBaseType("AAAATHIDEMO.Models.Dongvat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Cat");
                });
#pragma warning restore 612, 618
        }
    }
}
